kind: ConfigMap
apiVersion: v1
metadata:
  name: srvc-pdb-config
  namespace: srvc-pdb
data:
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"

  REDIS_ADDR: "gfp-cache.dpqsci.0001.euw3.cache.amazonaws.com:6379"
