kind: Deployment
apiVersion: apps/v1
metadata:
  name: srvc-pdb
  namespace: srvc-pdb
  labels:
    app: srvc-pdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srvc-pdb
  template:
    metadata:
      labels:
        app: srvc-pdb
    spec:
      containers:
      - name: srvc-pdb
        image: ghcr.io/therayquaza/gfp/srvc-pdb:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
