kind: ConfigMap
apiVersion: v1
metadata:
  name: srvc-account-config
  namespace: srvc-account
data:
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"

  DB_HOST: "xxx"
  DB_PORT: "5432"
  DB_NAME: "xxx"

  JWT_SECRET: "xxx"