kind: Deployment
apiVersion: apps/v1
metadata:
  name: srvc-account
  namespace: srvc-account
  labels:
    app: srvc-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srvc-account
  template:
    metadata:
      labels:
        app: srvc-account
    spec:
      containers:
      - name: srvc-account
        image: ghcr.io/therayquaza/gfp/srvc-account:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: srvc-account-config
        - secretRef:
            name: srvc-account-secret
