kind: Secret
apiVersion: v1
metadata:
  name: srvc-account-secret
  namespace: srvc-account
type: Opaque
data:
  DB_USER: "bXl1c2VybmFtZQo="
  DB_PASSWORD: "eW91cnNlY3VyZXBhc3N3b3JkCg=="

  JWT_SECRET: "eW91cnNlY3VyZXBhc3N3b3JkCg=="
